/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CorretorRouteImport } from './routes/corretor'
import { Route as CorrespondenteRouteImport } from './routes/correspondente'
import { Route as ClienteRouteImport } from './routes/cliente'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CorretorIndexRouteImport } from './routes/corretor.index'
import { Route as CorrespondenteIndexRouteImport } from './routes/correspondente.index'
import { Route as ClienteIndexRouteImport } from './routes/cliente.index'
import { Route as CorretorRelatoriosRouteImport } from './routes/corretor.relatorios'
import { Route as CorretorOperacionalRouteImport } from './routes/corretor.operacional'
import { Route as CorretorFinanceiroRouteImport } from './routes/corretor.financeiro'
import { Route as CorretorCrmRouteImport } from './routes/corretor.crm'
import { Route as CorrespondenteOperacionalRouteImport } from './routes/correspondente.operacional'
import { Route as CorrespondenteGestaoRouteImport } from './routes/correspondente.gestao'
import { Route as CorrespondenteFinanceiroRouteImport } from './routes/correspondente.financeiro'
import { Route as CorrespondenteCrmRouteImport } from './routes/correspondente.crm'

const CorretorRoute = CorretorRouteImport.update({
  id: '/corretor',
  path: '/corretor',
  getParentRoute: () => rootRouteImport,
} as any)
const CorrespondenteRoute = CorrespondenteRouteImport.update({
  id: '/correspondente',
  path: '/correspondente',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteRoute = ClienteRouteImport.update({
  id: '/cliente',
  path: '/cliente',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CorretorIndexRoute = CorretorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CorretorRoute,
} as any)
const CorrespondenteIndexRoute = CorrespondenteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CorrespondenteRoute,
} as any)
const ClienteIndexRoute = ClienteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClienteRoute,
} as any)
const CorretorRelatoriosRoute = CorretorRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => CorretorRoute,
} as any)
const CorretorOperacionalRoute = CorretorOperacionalRouteImport.update({
  id: '/operacional',
  path: '/operacional',
  getParentRoute: () => CorretorRoute,
} as any)
const CorretorFinanceiroRoute = CorretorFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => CorretorRoute,
} as any)
const CorretorCrmRoute = CorretorCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => CorretorRoute,
} as any)
const CorrespondenteOperacionalRoute =
  CorrespondenteOperacionalRouteImport.update({
    id: '/operacional',
    path: '/operacional',
    getParentRoute: () => CorrespondenteRoute,
  } as any)
const CorrespondenteGestaoRoute = CorrespondenteGestaoRouteImport.update({
  id: '/gestao',
  path: '/gestao',
  getParentRoute: () => CorrespondenteRoute,
} as any)
const CorrespondenteFinanceiroRoute =
  CorrespondenteFinanceiroRouteImport.update({
    id: '/financeiro',
    path: '/financeiro',
    getParentRoute: () => CorrespondenteRoute,
  } as any)
const CorrespondenteCrmRoute = CorrespondenteCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => CorrespondenteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cliente': typeof ClienteRouteWithChildren
  '/correspondente': typeof CorrespondenteRouteWithChildren
  '/corretor': typeof CorretorRouteWithChildren
  '/correspondente/crm': typeof CorrespondenteCrmRoute
  '/correspondente/financeiro': typeof CorrespondenteFinanceiroRoute
  '/correspondente/gestao': typeof CorrespondenteGestaoRoute
  '/correspondente/operacional': typeof CorrespondenteOperacionalRoute
  '/corretor/crm': typeof CorretorCrmRoute
  '/corretor/financeiro': typeof CorretorFinanceiroRoute
  '/corretor/operacional': typeof CorretorOperacionalRoute
  '/corretor/relatorios': typeof CorretorRelatoriosRoute
  '/cliente/': typeof ClienteIndexRoute
  '/correspondente/': typeof CorrespondenteIndexRoute
  '/corretor/': typeof CorretorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/correspondente/crm': typeof CorrespondenteCrmRoute
  '/correspondente/financeiro': typeof CorrespondenteFinanceiroRoute
  '/correspondente/gestao': typeof CorrespondenteGestaoRoute
  '/correspondente/operacional': typeof CorrespondenteOperacionalRoute
  '/corretor/crm': typeof CorretorCrmRoute
  '/corretor/financeiro': typeof CorretorFinanceiroRoute
  '/corretor/operacional': typeof CorretorOperacionalRoute
  '/corretor/relatorios': typeof CorretorRelatoriosRoute
  '/cliente': typeof ClienteIndexRoute
  '/correspondente': typeof CorrespondenteIndexRoute
  '/corretor': typeof CorretorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cliente': typeof ClienteRouteWithChildren
  '/correspondente': typeof CorrespondenteRouteWithChildren
  '/corretor': typeof CorretorRouteWithChildren
  '/correspondente/crm': typeof CorrespondenteCrmRoute
  '/correspondente/financeiro': typeof CorrespondenteFinanceiroRoute
  '/correspondente/gestao': typeof CorrespondenteGestaoRoute
  '/correspondente/operacional': typeof CorrespondenteOperacionalRoute
  '/corretor/crm': typeof CorretorCrmRoute
  '/corretor/financeiro': typeof CorretorFinanceiroRoute
  '/corretor/operacional': typeof CorretorOperacionalRoute
  '/corretor/relatorios': typeof CorretorRelatoriosRoute
  '/cliente/': typeof ClienteIndexRoute
  '/correspondente/': typeof CorrespondenteIndexRoute
  '/corretor/': typeof CorretorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cliente'
    | '/correspondente'
    | '/corretor'
    | '/correspondente/crm'
    | '/correspondente/financeiro'
    | '/correspondente/gestao'
    | '/correspondente/operacional'
    | '/corretor/crm'
    | '/corretor/financeiro'
    | '/corretor/operacional'
    | '/corretor/relatorios'
    | '/cliente/'
    | '/correspondente/'
    | '/corretor/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/correspondente/crm'
    | '/correspondente/financeiro'
    | '/correspondente/gestao'
    | '/correspondente/operacional'
    | '/corretor/crm'
    | '/corretor/financeiro'
    | '/corretor/operacional'
    | '/corretor/relatorios'
    | '/cliente'
    | '/correspondente'
    | '/corretor'
  id:
    | '__root__'
    | '/'
    | '/cliente'
    | '/correspondente'
    | '/corretor'
    | '/correspondente/crm'
    | '/correspondente/financeiro'
    | '/correspondente/gestao'
    | '/correspondente/operacional'
    | '/corretor/crm'
    | '/corretor/financeiro'
    | '/corretor/operacional'
    | '/corretor/relatorios'
    | '/cliente/'
    | '/correspondente/'
    | '/corretor/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClienteRoute: typeof ClienteRouteWithChildren
  CorrespondenteRoute: typeof CorrespondenteRouteWithChildren
  CorretorRoute: typeof CorretorRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/corretor': {
      id: '/corretor'
      path: '/corretor'
      fullPath: '/corretor'
      preLoaderRoute: typeof CorretorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/correspondente': {
      id: '/correspondente'
      path: '/correspondente'
      fullPath: '/correspondente'
      preLoaderRoute: typeof CorrespondenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliente': {
      id: '/cliente'
      path: '/cliente'
      fullPath: '/cliente'
      preLoaderRoute: typeof ClienteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corretor/': {
      id: '/corretor/'
      path: '/'
      fullPath: '/corretor/'
      preLoaderRoute: typeof CorretorIndexRouteImport
      parentRoute: typeof CorretorRoute
    }
    '/correspondente/': {
      id: '/correspondente/'
      path: '/'
      fullPath: '/correspondente/'
      preLoaderRoute: typeof CorrespondenteIndexRouteImport
      parentRoute: typeof CorrespondenteRoute
    }
    '/cliente/': {
      id: '/cliente/'
      path: '/'
      fullPath: '/cliente/'
      preLoaderRoute: typeof ClienteIndexRouteImport
      parentRoute: typeof ClienteRoute
    }
    '/corretor/relatorios': {
      id: '/corretor/relatorios'
      path: '/relatorios'
      fullPath: '/corretor/relatorios'
      preLoaderRoute: typeof CorretorRelatoriosRouteImport
      parentRoute: typeof CorretorRoute
    }
    '/corretor/operacional': {
      id: '/corretor/operacional'
      path: '/operacional'
      fullPath: '/corretor/operacional'
      preLoaderRoute: typeof CorretorOperacionalRouteImport
      parentRoute: typeof CorretorRoute
    }
    '/corretor/financeiro': {
      id: '/corretor/financeiro'
      path: '/financeiro'
      fullPath: '/corretor/financeiro'
      preLoaderRoute: typeof CorretorFinanceiroRouteImport
      parentRoute: typeof CorretorRoute
    }
    '/corretor/crm': {
      id: '/corretor/crm'
      path: '/crm'
      fullPath: '/corretor/crm'
      preLoaderRoute: typeof CorretorCrmRouteImport
      parentRoute: typeof CorretorRoute
    }
    '/correspondente/operacional': {
      id: '/correspondente/operacional'
      path: '/operacional'
      fullPath: '/correspondente/operacional'
      preLoaderRoute: typeof CorrespondenteOperacionalRouteImport
      parentRoute: typeof CorrespondenteRoute
    }
    '/correspondente/gestao': {
      id: '/correspondente/gestao'
      path: '/gestao'
      fullPath: '/correspondente/gestao'
      preLoaderRoute: typeof CorrespondenteGestaoRouteImport
      parentRoute: typeof CorrespondenteRoute
    }
    '/correspondente/financeiro': {
      id: '/correspondente/financeiro'
      path: '/financeiro'
      fullPath: '/correspondente/financeiro'
      preLoaderRoute: typeof CorrespondenteFinanceiroRouteImport
      parentRoute: typeof CorrespondenteRoute
    }
    '/correspondente/crm': {
      id: '/correspondente/crm'
      path: '/crm'
      fullPath: '/correspondente/crm'
      preLoaderRoute: typeof CorrespondenteCrmRouteImport
      parentRoute: typeof CorrespondenteRoute
    }
  }
}

interface ClienteRouteChildren {
  ClienteIndexRoute: typeof ClienteIndexRoute
}

const ClienteRouteChildren: ClienteRouteChildren = {
  ClienteIndexRoute: ClienteIndexRoute,
}

const ClienteRouteWithChildren =
  ClienteRoute._addFileChildren(ClienteRouteChildren)

interface CorrespondenteRouteChildren {
  CorrespondenteCrmRoute: typeof CorrespondenteCrmRoute
  CorrespondenteFinanceiroRoute: typeof CorrespondenteFinanceiroRoute
  CorrespondenteGestaoRoute: typeof CorrespondenteGestaoRoute
  CorrespondenteOperacionalRoute: typeof CorrespondenteOperacionalRoute
  CorrespondenteIndexRoute: typeof CorrespondenteIndexRoute
}

const CorrespondenteRouteChildren: CorrespondenteRouteChildren = {
  CorrespondenteCrmRoute: CorrespondenteCrmRoute,
  CorrespondenteFinanceiroRoute: CorrespondenteFinanceiroRoute,
  CorrespondenteGestaoRoute: CorrespondenteGestaoRoute,
  CorrespondenteOperacionalRoute: CorrespondenteOperacionalRoute,
  CorrespondenteIndexRoute: CorrespondenteIndexRoute,
}

const CorrespondenteRouteWithChildren = CorrespondenteRoute._addFileChildren(
  CorrespondenteRouteChildren,
)

interface CorretorRouteChildren {
  CorretorCrmRoute: typeof CorretorCrmRoute
  CorretorFinanceiroRoute: typeof CorretorFinanceiroRoute
  CorretorOperacionalRoute: typeof CorretorOperacionalRoute
  CorretorRelatoriosRoute: typeof CorretorRelatoriosRoute
  CorretorIndexRoute: typeof CorretorIndexRoute
}

const CorretorRouteChildren: CorretorRouteChildren = {
  CorretorCrmRoute: CorretorCrmRoute,
  CorretorFinanceiroRoute: CorretorFinanceiroRoute,
  CorretorOperacionalRoute: CorretorOperacionalRoute,
  CorretorRelatoriosRoute: CorretorRelatoriosRoute,
  CorretorIndexRoute: CorretorIndexRoute,
}

const CorretorRouteWithChildren = CorretorRoute._addFileChildren(
  CorretorRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClienteRoute: ClienteRouteWithChildren,
  CorrespondenteRoute: CorrespondenteRouteWithChildren,
  CorretorRoute: CorretorRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
