// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nrkhulowokeeszgkvhdm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ya2h1bG93b2tlZXN6Z2t2aGRtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODE1OTI2MjQsImV4cCI6MjA5NzE2ODYyNH0._ceYfOuU6EI1mE95rgmkhySs7RoupvfHvexvAPWQqgU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});